### ISSUE TITLE
picopayments-cli sync IndexError: pop from empty list

### ISSUE THREAD

**Issue by littleskunk** [F483/picopayments-cli-python#6] opened 2016-12-24 14:49 UTC
```
root@micropayment:~/.picopayments# picopayments-cli --testnet sync
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:732: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html (This warning will only appear once by default.)
  InsecureRequestWarning)
script failed for unknown reason
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 60, in pop
    return super(Stack, self).pop(*args, **kwargs)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 172, in eval_script
    f(stack)
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/microcode.py", line 508, in do_OP_HASH160
    stack.append(hash160(stack.pop()))
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 62, in pop
    raise ScriptError("pop from empty stack")
pycoin.tx.script.ScriptError: pop from empty stack
script failed for unknown reason
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 60, in pop
    return super(Stack, self).pop(*args, **kwargs)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 172, in eval_script
    f(stack)
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/microcode.py", line 508, in do_OP_HASH160
    stack.append(hash160(stack.pop()))
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 62, in pop
    raise ScriptError("pop from empty stack")
pycoin.tx.script.ScriptError: pop from empty stack
script failed for unknown reason
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 60, in pop
    return super(Stack, self).pop(*args, **kwargs)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 172, in eval_script
    f(stack)
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/microcode.py", line 508, in do_OP_HASH160
    stack.append(hash160(stack.pop()))
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 62, in pop
    raise ScriptError("pop from empty stack")
pycoin.tx.script.ScriptError: pop from empty stack
script failed for unknown reason
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 60, in pop
    return super(Stack, self).pop(*args, **kwargs)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 172, in eval_script
    f(stack)
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/microcode.py", line 508, in do_OP_HASH160
    stack.append(hash160(stack.pop()))
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 62, in pop
    raise ScriptError("pop from empty stack")
pycoin.tx.script.ScriptError: pop from empty stack
{
    "08ed5def131032029d7194622f59a058a62a75672f2b7c6c8b7e933a34efba87": {
        "received_payments": [],
        "txids": []
    },
    "aeab3f226b4660d93594884924a4b3e2dccdb98c1e246d29647fcbbd2d35dff6": {
        "received_payments": [],
        "txids": []
    }
}
```

**Comment by F483** [comment] 2017-01-03 14:48
Duplicate of https://github.com/F483/picopayments-cli-python/issues/4

**Closed by F483** 2017-01-03 14:48 UTC
