### ISSUE TITLE
picopayments-cli connect list index out of range

### ISSUE THREAD

**Issue by littleskunk** [F483/picopayments-cli-python#5] opened 2016-12-24 13:51 UTC
```
root@micropayment:~/.picopayments# picopayments-cli --testnet connect XCP 100000                                                                                                                                                             0
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:732: InsecureRequestWar                                                                                                                                                             ning: Unverified HTTPS request is being made. Adding certificate verification is                                                                                                                                                              strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html                                                                                                                                                              (This warning will only appear once by default.)
  InsecureRequestWarning)
script failed for unknown reason
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 66,                                                                                                                                                              in __getitem__
    return super(Stack, self).__getitem__(*args, **kwargs)
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 172                                                                                                                                                             , in eval_script
    f(stack)
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/microcode.py", l                                                                                                                                                             ine 195, in do_OP_DUP
    stack.append(stack[-1])
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 68,                                                                                                                                                              in __getitem__
    raise ScriptError("getitem out of range")
pycoin.tx.script.ScriptError: getitem out of range
script failed for unknown reason
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 66,                                                                                                                                                              in __getitem__
    return super(Stack, self).__getitem__(*args, **kwargs)
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 172                                                                                                                                                             , in eval_script
    f(stack)
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/microcode.py", l                                                                                                                                                             ine 195, in do_OP_DUP
    stack.append(stack[-1])
  File "/usr/local/lib/python3.4/dist-packages/pycoin/tx/script/vm.py", line 68,                                                                                                                                                              in __getitem__
    raise ScriptError("getitem out of range")
pycoin.tx.script.ScriptError: getitem out of range
{
    "handle": "08ed5def131032029d7194622f59a058a62a75672f2b7c6c8b7e933a34efba87"                                                                                                                                                             ,
    "send_deposit_txid": "a4d2ac8a2a42dae035415ed52b74381d78c71dcf8d3f08346a17f6                                                                                                                                                             7db66966ff"
}
```

**Comment by F483** [comment] 2017-01-03 14:49
Duplicate of https://github.com/F483/picopayments-cli-python/issues/4

**Closed by F483** 2017-01-03 14:49 UTC
